packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@changesets/changelog-github": 0.6.0
  "@changesets/cli": 2.30.0
  "@commitlint/cli": ^20.5.0
  "@commitlint/config-conventional": ^20.5.0
  "@types/node": ^24
  lefthook: ^2.1.4
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
