packages:
  - .

catalog:
  "@changesets/changelog-github": 0.6.0
  "@changesets/cli": 2.30.0
  "@commitlint/cli": ^20.5.0
  "@commitlint/config-conventional": ^20.5.0
  "@types/node": ^24
  "@typescript/native-preview": 7.0.0-dev.20260323.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
